config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list_id, message: "This Movie is already in a list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :find_list, except: [:destroy]
  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def find_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :comment %>
    <%= f.association :movie %>
  </div>
  <div class="form-actions btn-dark">
    <%= f.button :submit, "Add a Movie"%>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
<div class="main-container">
  <h1>Create a bookmark</h1>

  <%= render 'form', bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar-lewagon navbar-collapse navbar-brand flex">
      <p><%= link_to "Movie Lists", lists_path  %></p>
      <button class="btn btn-dark"><%= link_to "Create a List", new_list_path  %></button>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions btn btn-dark">
    <%= f.button :submit, "Create a Movie List" %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="banner home">
  <h1>Movie Club</h1>
</div>

<div class="main-container">
  <h2>What are you in the Mood for?</h2>
  <div class="card-container-flex">
    <% @lists.each do |list| %>
        <div class="list-card">
          <div><%= cl_image_tag list.photo.key, height: 200, width: 300, crop: :fill %></div>
          <div class="vertical-align"><%= link_to list.name, list %></div>
        </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="main-container">
  <h2>Create a list</h2>

  <%= render 'form', list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: url(<%= url_for @list.photo %>)"></div>
<div class="main-container">
  <h2><%= @list.name %></h2>
  <div class="row">

    <div class="col-8 flex cards">
      <% @list.movies.each do |movie| %>
        <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <div class="movie-card">
          <div class="card-top">
            <div><%= image_tag movie.poster_url, alt: movie.title %></div>
          </div>
          <div class="card-bottom flex">
            <div class="bottom-left">
              <h4><%= movie.title %></h4>
              <p><%= bookmark.comment %></p>
            </div>
            <%= link_to bookmark, method: :delete, data: { confirm: 'Are you sure?' }, class: 'card-remove-link' do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>



    <div class="col-4">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <%= f.association :movie %>
          <%= f.input :comment %>
        </div>
        <div class="form-actions btn-dark">
          <%= f.button :submit, "Add a Movie"%>
        </div>
      <% end %>
    </div>
  </div>
</div>